[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps = 
    https://github.com/clearwater/SwitecX25.git
    https://github.com/stm32duino/VL53L4CX.git